name: beniget
language: python
language_version: "3.7"
analysis_runtime: "Python >=3.10"
target_files: ["legacy_api/**/*.py"]
trigger:
  command: "python tool-triggers/scripts/run_beniget.py legacy_api"
