name: coverage-py-beniget
language: python
language_version: "3.5"
analysis_runtime: "Python >=3.10"
target_files: ["legacy_api/**/*.py", "tests/**/*.py"]
trigger:
  command: "coverage run -m unittest discover -s tests && python tool-triggers/scripts/run_beniget.py legacy_api"
